<div class="page-title"><h1><?php echo $this->__('My Credit Cards') ?></h1></div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="box-account">
	<?php $_storedCards = $this->getStoredCards(); ?>
	<div class="box-head"><h2><?php echo $this->__('Credit Cards') ?></h2></div>
	<?php if( $_storedCards && (count($_storedCards) > 0) ): ?>
	<table class="data-table" id="stored-cards-table">
		<col />
		<col width="1" />
		<col width="1" />
		<col width="1" />
		<thead>
			<tr>
				<th><?php echo $this->__('Credit Card') ?></th>
				<th><?php echo $this->__('Expiration Date') ?></th>
				<th><?php echo $this->__('Last Used') ?></th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($_storedCards as $_storedCard): ?>
			<tr>
				<td><?php echo Mage::helper('securepay')->translateCcType($_storedCard->getCcType()) ?> (<?php echo sprintf('xxxx-%s', $_storedCard->getCcLast4()) ?>)</td>
				<td class="a-center"><span class="nobr"><?php echo sprintf('%02d',$_storedCard->getCcExpMonth()); ?>/<?php echo $_storedCard->getCcExpYear() ?></span></td>
				<td class="a-center"><span class="nobr"><?php echo Mage::app()->getLocale()->date($_storedCard->getUpdatedDate())->toString('MMM-dd-yyyy') ?></span></td>
				<td class="a-center">
					<span class="nobr">
						<a href="<?php echo $this->getDeleteUrl($_storedCard) ?>" onclick="return confirm('<?php echo $this->__('Are you sure?') ?>')"><?php echo $this->__('Delete') ?></a>
					</span>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<script type="text/javascript">decorateTable('stored-cards-table')</script>
	<?php else: ?>
		<p><?php echo $this->__('You have not saved any credit card details.'); ?></p>
	<?php endif; ?>
</div>